name: Merge JSON Data with Differences

on:
  push:
    branches:
      - main

jobs:
  merge-and-diff-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

    - name: Fetch and merge JSON data
      run: |
        # Fetch JSON data from API
        curl -s -H "Authorization: 5c672e8056d802c52d3398e1376174f0" \
             -H "Cookie: sid=s%3A5c672e8056d802c52d3398e1376174f0.Nvn4B0oVX%2BeUAIP7cSqwkqp7%2BIr8DwL1AhXhpRKs7r8" \
             "https://paratranz.cn/api/projects/8340/files" > files.json

        # Initialize empty array for merging
        echo '[]' > merged_data.json

        # Loop through each file ID and merge JSON data
        jq -c '.[] | .id' files.json | while read -r file_id; do
          curl -s -H "Authorization: 5c672e8056d802c52d3398e1376174f0" \
               -H "Cookie: sid=s%3A5c672e8056d802c52d3398e1376174f0.Nvn4B0oVX%2BeUAIP7cSqwkqp7%2BIr8DwL1AhXhpRKs7r8" \
               "https://paratranz.cn/api/projects/8340/files/${file_id}/translation" > temp.json
          
          # Merge into the merged_data.json file
          jq -s '.[0] + .[1]' merged_data.json temp.json > temp_merged.json
          mv temp_merged.json merged_data.json
        done

        mv merged_data.json final.json

    - name: Upload final JSON
      uses: actions/upload-artifact@v3
      with:
        name: final-json
        path: final.json
