name: 删除Workflow Run记录，释放空间

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Delete Workflow Runs Logs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #!/bin/bash

          # Get repository owner and name
          REPO="${GITHUB_REPOSITORY}"
          echo "Repository: $REPO"

          # List workflow runs and delete logs
          while :
          do
            # Fetch workflow runs
            RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                          "https://api.github.com/repos/$REPO/actions/runs?per_page=100")

            # Extract run IDs
            RUN_IDS=$(echo "$RESPONSE" | jq -r '.workflow_runs[].id')

            if [ -z "$RUN_IDS" ]; then
              echo "No more workflow runs found."
              break
            fi

            # Delete logs for each run
            for RUN_ID in $RUN_IDS
            do
              echo "Deleting logs for workflow run ID: $RUN_ID"
              curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                   "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/logs"
            done
          done

          echo "All workflow run logs deleted successfully."
