name: Delete All Workflow Runs Logs

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Delete Workflow Runs Logs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install required package
          npm install @octokit/rest

          # JavaScript script to delete workflow run logs
          node <<EOF
          import { Octokit } from "@octokit/rest";

          const octokit = new Octokit({
            auth: process.env.GITHUB_TOKEN,
          });

          const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");

          (async () => {
            try {
              const { data: { workflow_runs } } = await octokit.rest.actions.listWorkflowRunsForRepo({
                owner,
                repo,
                per_page: 100,
              });

              if (workflow_runs.length === 0) {
                console.log("No workflow runs found.");
                return;
              }

              for (const run of workflow_runs) {
                console.log(`Deleting logs for workflow run: ${run.id}`);
                await octokit.rest.actions.deleteWorkflowRunLogs({
                  owner,
                  repo,
                  run_id: run.id,
                });
              }
              console.log("All workflow run logs deleted successfully.");
            } catch (error) {
              console.error("Error deleting workflow run logs:", error.message);
            }
          })();
          EOF
