name: Delete All Workflow Runs

on:
  workflow_dispatch:

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 更新为符合要求的版本

      - name: Delete Workflow Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install required package
          npm install @octokit/rest

          # JavaScript script to delete workflow runs
          node <<EOF
          const { Octokit } = require('@octokit/rest');

          const octokit = new Octokit({
            auth: process.env.GITHUB_TOKEN,
          });

          const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');

          (async () => {
            try {
              const { data: { workflow_runs } } = await octokit.rest.actions.listWorkflowRunsForRepo({
                owner,
                repo,
                per_page: 100,
              });

              for (const run of workflow_runs) {
                console.log(`Deleting workflow run: ${run.id}`);
                await octokit.rest.actions.deleteWorkflowRun({
                  owner,
                  repo,
                  run_id: run.id,
                });
              }
              console.log('All workflow runs deleted successfully.');
            } catch (error) {
              console.error('Error deleting workflow runs:', error.message);
            }
          })();
          EOF
