name: Convert INI to JSON and Compare with Final

on:
  push:
    branches:
      - main

jobs:
  convert-compare-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 使用 v4 版本

    - name: Set up Node.js
      uses: actions/setup-node@v4  # 使用 v4 版本
      with:
        node-version: '20'  # 使用 Node.js 20 版本

    - name: Install dependencies
      run: |
        npm install iconv-lite ini axios

    - name: Run Node.js script
      run: |
        node script.js
      env:
        AUTHORIZATION: ${{ secrets.AUTHORIZATION }}  # 从 GitHub Secrets 获取 AUTHORIZATION

    - name: Create ZIP file of JSON outputs
      run: |
        zip output_files.zip global.json final.json difference.json

    - name: Upload ZIP file
      uses: actions/upload-artifact@v4  # 使用 v4 版本
      with:
        name: json_files_zip
