name: Convert INI to JSON and Compare with Final

on:
  push:
    branches:
      - main

jobs:
  convert-compare-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # 使用适合您的 Node.js 版本

    - name: Install dependencies
      run: |
        npm install iconv-lite ini axios

    - name: Run Node.js script
      run: |
        node script.js

    - name: Create ZIP file of JSON outputs
      run: |
        zip output_files.zip global.json final.json difference.json

    - name: Upload ZIP file
      uses: actions/upload-artifact@v3
      with:
        name: json_files_zip
        path: output_files.zip
