name: Convert INI to JSON and Compare with Final

on:
  push:
    branches:
      - main

jobs:
  convert-compare-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # 使用适合您的版本

    - name: Install dependencies
      run: |
        npm install axios ini

    - name: Run Node.js script
      run: |
        node script.js

    - name: Upload global.json
      uses: actions/upload-artifact@v3
      with:
        name: global.json
        path: global.json
    
    - name: Upload final.json
      uses: actions/upload-artifact@v3
      with:
        name: final.json
        path: final.json
    
    - name: Upload difference.json
      uses: actions/upload-artifact@v3
      with:
        name: difference.json
        path: difference.json
