name: 对比ini差异

on:
  push:
    branches:
      - main
    paths:
      - "global.ini"  # 仅在 global.ini 修改时触发
  workflow_dispatch:   # 增加手动触发器

jobs:
  convert-compare-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 使用 v4 版本

    - name: Set up Node.js
      uses: actions/setup-node@v4  # 使用 v4 版本
      with:
        node-version: '20'  # 使用 Node.js 20 版本

    - name: Install dependencies
      run: |
        npm install iconv-lite ini axios

    - name: Run Node.js script
      run: |
        node script.js
      env:
        AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
        
    - name: Upload JSON files
      uses: actions/upload-artifact@v4  # 使用 v4 版本
      with:
        name: json_files_zip
        path: |
          global.json
          final.json
          difference.json
