name: Convert INI to JSON and Compare with Final

on:
  push:
    branches:
      - main

jobs:
  convert-compare-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

    - name: Convert INI to JSON
      run: |
        # Initialize the JSON array
        echo "[" > global.json

        # Convert INI to JSON format, removing BOM and illegal characters
        while IFS= read -r line; do
          # Remove BOM if present
          line=$(echo "$line" | sed 's/^\xEF\xBB\xBF//')
          
          if [[ "$line" == *"="* ]]; then
            key=$(echo "$line" | cut -d '=' -f 1 | sed 's/["\\]/\\&/g; s/[^[:print:]]//g')
            original=$(echo "$line" | cut -d '=' -f 2- | sed 's/["\\]/\\&/g; s/[^[:print:]]//g')
            echo "  {\"key\": \"$key\", \"original\": \"$original\", \"translation\": \"\", \"context\": \"\"}," >> global.json
          fi
        done < <(iconv -f UTF-8 -t UTF-8 -c global.ini)

        # Remove the trailing comma and close the JSON array
        sed -i '$ s/,$//' global.json
        echo "]" >> global.json

    - name: Fetch and merge JSON data
      run: |
        # 从 API 获取 JSON 数据
        curl -s -H "Authorization: 5c672e8056d802c52d3398e1376174f0" \
             -H "Cookie: sid=s%3A5c672e8056d802c52d3398e1376174f0.Nvn4B0oVX%2BeUAIP7cSqwkqp7%2BIr8DwL1AhXhpRKs7r8" \
             "https://paratranz.cn/api/projects/8340/files" > files.json
    
        # 初始化空数组用于合并
        echo '[]' > merged_data.json
    
        # 循环遍历每个文件并合并 JSON 数据
        jq -c '.[] | .key' files.json | while read -r key; do
          curl -s -H "Authorization: 5c672e8056d802c52d3398e1376174f0" \
               -H "Cookie: sid=s%3A5c672e8056d802c52d3398e1376174f0.Nvn4B0oVX%2BeUAIP7cSqwkqp7%2BIr8DwL1AhXhpRKs7r8" \
               "https://paratranz.cn/api/projects/8340/files/${key}/translation" > temp.json
          
          # 使用jq合并数据，通过key合并内容
          jq -s 'reduce .[] as $item ({}; .[$item.key] = (.[$item.key] // {} | . + $item))' merged_data.json temp.json > temp_merged.json
          mv temp_merged.json merged_data.json
        done
    
        mv merged_data.json final.json

    - name: Compare global JSON with final JSON
      run: |
        # Compare global.json with final.json, keeping final.json's original text in case of differences
        jq --argfile final final.json --argfile global global.json \
          '[.[] as $g | $final[] | select(.key == $g.key and .original != $g.original)]' > difference.json

    - name: Upload global.json
      uses: actions/upload-artifact@v3
      with:
        name: global.json
        path: global.json
    
    - name: Upload final.json
      uses: actions/upload-artifact@v3
      with:
        name: final.json
        path: final.json
    
    - name: Upload difference.json
      uses: actions/upload-artifact@v3
      with:
        name: difference.json
        path: difference.json
