name: 同步fork的localizationData

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    steps:
    - uses: actions/checkout@v4  # 拉取仓库代码

    - uses: tgymnich/fork-sync@v2.0 #同步fork仓库main分支
      with:
        token: ${{ secrets.GH_TOKEN }}
        owner: herokillerJ
        repo: ${{ secrets.GH_FORK_REPO }}
        base: main
        head: main
        auto_approve: true

    - uses: tgymnich/fork-sync@v2.0 #同步fork仓库cn_e分支
      with:
        token: ${{ secrets.GH_TOKEN }}
        owner: ${{ secrets.GH_FORK_USERNAME }}
        repo: ${{ secrets.GH_FORK_REPO }}
        base: cn_e
        head: cn_e
        auto_approve: true

    - uses: tgymnich/fork-sync@v2.0 #同步fork仓库cn_e分支
      with:
        token: ${{ secrets.GH_TOKEN }}
        owner: ${{ secrets.GH_FORK_USERNAME }}
        repo: ${{ secrets.GH_FORK_REPO }}
        base: cn_en
        head: cn_en
        auto_approve: true
