name: 发行汉化版本（旧脚本/已弃用）

on:
  workflow_dispatch: # 允许手动触发

jobs:
  merge_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # 使用 Node.js 版本

    - name: Install dependencies
      run: npm install axios

    - name: Merge translations and convert to INI
      run: node merge_and_convert.js
      env:
        AUTHORIZATION: ${{ secrets.AUTHORIZATION }}

    - name: Upload INI files
      uses: actions/upload-artifact@v3
      with:
        name: ini-files
        path: final_output/*.ini
