name: java版发行汉化(不发布)

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # 拉取仓库代码

    - name: 加载缓存
      uses: actions/cache@v4
      with:
        path: cached_files  # 缓存的文件目录
        key: files-cache-${{ runner.os }}-${{ hashFiles('cache/paratranz/paratranz_files_metadata.info') }}
        restore-keys: files-cache-${{ runner.os }}

    - name: 准备环境 # 配置 JDK 版本
      uses: actions/setup-java@v4 
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: 'java/pom.xml'

    - name: 编译 # 编译项目
      run: mvn -f java/pom.xml compile

    - name: 复制依赖 # 复制依赖
      run: mvn -f java/pom.xml dependency:copy-dependencies -DoutputDirectory=target/dependency

    - name: 执行脚本 # 执行
      run: java -cp "java/target/classes:java/target/dependency/*" cn.citizenwiki.RestoreParatranzCache  # 运行指定类
      env:
        PZ_TOKEN: ${{ secrets.PZ_TOKEN }}
        PZ_PROJECT_ID: ${{ secrets.PZ_PROJECT_ID }}

    - name: 上传生成的文件 # 上传文件,在action页面可以下载
      uses: actions/upload-artifact@v4
      with:
        name: ini-files
        path: cache/*
